package model

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"
)

// Default returns a Config populated with sensible, hardware-agnostic
// defaults. Discovery fills in Sensors/Groups on top of this.
func Default() Config {
	return Config{
		Version:      1,
		IpmitoolPath: "ipmitool",
		SmartctlPath: "smartctl",
		PollInterval: Duration(5 * time.Second),
		Dell: DellRaw{
			ManualModeCmd:  []string{"0x30", "0x30", "0x01", "0x00"},
			AutoModeCmd:    []string{"0x30", "0x30", "0x01", "0x01"},
			SetSpeedPrefix: []string{"0x30", "0x30", "0x02"},
			Zones:          []string{"0xff"},
		},
		Smoothing: Smoothing{
			EMAAlpha:          0.35,
			MaxStepUpPct:      6,
			MaxStepDownPct:    3,
			MinChangePct:      1,
			MinFanPct:         12,
			MaxFanPct:         100,
			RampDownHoldTicks: 6, // 6 ticks * 5s default poll = 30s hold before ramping down further
		},
		Safety: Safety{
			GlobalCritC:          75,
			RecoverHysteresisC:   8,
			RecoverGoodTicks:     12, // ~1 minute at 5s poll
			MaxConsecutiveErrors: 5,
			RevertOnExit:         true,
		},
		Logging: Logging{Level: "info"},
		MQTT: MQTT{
			Enabled:         false,
			ClientID:        "dellfanctl",
			BaseTopic:       "", // computed as "dellfanctl/<node_id>" if left empty
			NodeID:          "", // computed from hostname if left empty
			DiscoveryPrefix: "homeassistant",
			QoS:             1,
		},
	}
}

// Load reads and validates a config file from path.
func Load(path string) (*Config, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading config: %w", err)
	}
	cfg := Default()
	if err := yaml.Unmarshal(b, &cfg); err != nil {
		return nil, fmt.Errorf("parsing config: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("invalid config %s: %w", path, err)
	}
	return &cfg, nil
}

// Save writes cfg to path as YAML, preceded by an explanatory header
// comment. Refuses to silently clobber an existing file unless overwrite is
// true.
func Save(path string, cfg *Config, overwrite bool) error {
	if !overwrite {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists (pass --force to overwrite)", path)
		}
	}
	b, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("encoding config: %w", err)
	}
	out := append([]byte(configHeader), b...)
	// 0600: the config can hold an mqtt.password, so it's root-only by
	// default rather than world-readable. os.WriteFile only applies this
	// mode when *creating* a new file, not when overwriting one that
	// already existed (e.g. from an older version, or before mqtt
	// support) with looser permissions, so Chmod explicitly rather than
	// relying on that.
	if err := os.WriteFile(path, out, 0o600); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}
	if err := os.Chmod(path, 0o600); err != nil {
		return fmt.Errorf("setting config file permissions: %w", err)
	}
	return nil
}

const configHeader = `# dellfanctl configuration.
#
# Generated by 'dellfanctl discover'. Review before enabling 'run':
#   - Check each sensor's "class" and "required" flag.
#   - Check group "curve" points (temp_c -> fan_pct) for your comfort/noise
#     tradeoff. Groups with enabled: false are ignored by the control loop.
#   - crit_c / safety.global_crit_c govern the fallback to iDRAC automatic
#     control; keep them well under your hardware's actual thermal limits.
#   - dell.zones controls how the "set fan speed" raw command is sent.
#     "0xff" (all zones) works on most 13G+ PowerEdge boards. If your fans
#     don't respond, try one byte per fan, e.g. ["0x00","0x01","0x02",...].
#
# Always test with 'dellfanctl run --dry-run' before running for real.

`
